env:
  es6: true
  node: true

extends: 'eslint:recommended'

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

rules:
  indent: [2, 2]
  comma-dangle: [2, "always-multiline"]
  quotes: [2, "double"]
  no-unreachable: [2]
  no-unexpected-multiline: [2]
  semi: [2, "never"]

  react/jsx-uses-vars: [2]
